- name: Configuring NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed
    args:
      chdir: /app

- name: Import app_prereq yml file
  ansible.builtin.import_tasks:
    file: app_prereq.yaml

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Import schema_setup yml file
  ansible.builtin.import_tasks:
    file: schema_setup.yaml

- name: Import systemd_setup yml file
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml