- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import schema_setup yml file
  ansible.builtin.import_tasks:
    file: app_prereq.yaml

- name: Install Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.tx
  args:
    chdir: /app

- name: Import schema_setup yml file
  ansible.builtin.import_tasks:
    file: systemd_setup.yaml