- name:
  when: schema_setup == "mongodb"
  block:
    - name: Copy MongoDB repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongodb_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js

- name:
  when: schema_setup == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{env}}.shipping.mysql.endpoint', region='us-east-1' ) }} -u{{ lookup('aws_ssm', '{{env}}.shipping.mysql.user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{env}}.shipping.mysql.password', region='us-east-1' ) }} < /app/schema/{{component}}.sql
